language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libblas-dev
            - liblapack-dev
            - mpich
            - libmpich-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - NETLIBROOT="/usr/lib"

script:
  - ls /usr/local/lib/libblas*
  - ls /usr/lib/libblas*
  - ls /lib/libblas*
  - source set_env.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
