language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          package:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

script:
  - source set_env.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
