language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          package:
            - g++-5
            - libblas-dev
            - liblapack-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - NETLIBROOT="/usr/local/lib"

script:
  - ls /usr/local/lib/libblas*
  - ls /usr/lib/libblas*
  - ls /lib/libblas*
  - source set_env.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
